name: Pipeline aula 02 - multiplicacao
on: 
  push:
    branches: 
      - main

# Na branch dev a lógica se mantém em push e pull request (CI) 
# Na branch main a lógica seria apenas um push (CD)

jobs: 

  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Gerar artefato ZIP
        run: zip -r pipeline-demo.zip . -x "node_modules/*" ".git/*"

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with: 
          name: codigo-buildado
          path: pipeline-demo.zip

  test: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm ci

      - name: Run Jest
        run: npm test

      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with: 
          name: codigo-buildado

      - name: Extrair artefato
        run: unzip -o pipeline-demo.zip

  deploy: 
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: production
    
    steps:
      - name: Simular deploy
        run: echo "Deploy realizado com sucesso"

